params:
  epochs: 30
  batch_size: 32
  input_shape: [28, 28]
  loss_functions: sparse_categorical_cross_entropy
  metrics: accuracy
  optimizer: SGD
  validation_data: 5000 

artifacts:
  artifacts_dir: artifacts
  model_dr: model
  plots_dir: plots
  checkpoint_dir: checkpoints

logs:
  logs_dir: log_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs


